name: Tagging

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  tagging:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: echo "value=$(jq -r '.version' deno.json)" >> "$GITHUB_OUTPUT"
        id: version
      - run: git tag "$TAG"
        env:
          TAG: ${{ steps.version.outputs.value }}
      - run: git push origin "$TAG" || true
        env:
          TAG: ${{ steps.version.outputs.value }}
